In [12]:
import pandas as pd

In [13]:
meta = pd.read_csv("../data/metaData.csv")
meta.head()

       lead_code  total_due dpd_bucket       state
0  LDSMFG_100000     126958      60-90   Karnataka
1  LDSMFG_100001     151867      30-60          UP
2  LDSMFG_100002     136932      60-90       Delhi
3  LDSMFG_100003     370838      30-60  Tamil Nadu
4  LDSMFG_100004     264178      60-90       Delhi

In [14]:
train = pd.read_csv("../data/train.csv")
train.head()

   id      lead_code   suggested_action  TARGET
0   1  LDSMFG_100000  ACTION_HUMAN_CALL    0.47
1   2  LDSMFG_100001       ACTION_FIELD    0.35
2   3  LDSMFG_100002  ACTION_HUMAN_CALL    0.09
3   4  LDSMFG_100003     ACTION_DIGITAL    0.40
4   5  LDSMFG_100004  ACTION_HUMAN_CALL    0.49

In [15]:
print("meta shape:", meta.shape)
print("train shape:", train.shape)

meta shape: (100000, 4)
train shape: (80000, 4)

In [16]:
train.columns

Index(['id', 'lead_code', 'suggested_action', 'TARGET'], dtype='object')

In [17]:
train["TARGET"].describe()

count    80000.000000
mean         0.448925
std          0.190518
min          0.000000
25%          0.330000
50%          0.430000
75%          0.580000
max          1.000000
Name: TARGET, dtype: float64

In [18]:
train["suggested_action"].value_counts()

suggested_action
ACTION_HUMAN_CALL    20116
ACTION_DIGITAL       20097
ACTION_BOT           20048
ACTION_FIELD         19739
Name: count, dtype: int64

In [19]:
train_merged = pd.merge(
    train,
    meta,
    on="lead_code",
    how="left"
)

train_merged.head()

,id,lead_code,suggested_action,TARGET,total_due,dpd_bucket,state
0,1,LDSMFG_100000,ACTION_HUMAN_CALL,0.47,126958,60-90,Karnataka
1,2,LDSMFG_100001,ACTION_FIELD,0.35,151867,30-60,UP
2,3,LDSMFG_100002,ACTION_HUMAN_CALL,0.09,136932,60-90,Delhi
3,4,LDSMFG_100003,ACTION_DIGITAL,0.40,370838,30-60,Tamil Nadu
4,5,LDSMFG_100004,ACTION_HUMAN_CALL,0.49,264178,60-90,Delhi

In [20]:
train_merged.isnull().sum()

id                  0
lead_code           0
suggested_action    0
TARGET              0
total_due           0
dpd_bucket          0
state               0
dtype: int64

In [21]:
train_merged.shape

(80000, 7)

In [22]:
train_merged.to_csv("../data/train_merged.csv", index=False)