In [1]:
import pandas as pd

In [2]:
wa = pd.read_csv("../data/whatsapp_activity.csv")
wa.head()

       lead_code     sent_at     status response_message              read_at
0  LDSMFG_124034  2025-01-10  DELIVERED              NaN                  NaN
1  LDSMFG_143014  2025-01-01  DELIVERED              NaN                  NaN
2  LDSMFG_192539  2025-01-20       READ              NaN  2025-01-20 11:00:00
3  LDSMFG_141327  2025-01-08       READ              NaN  2025-01-08 12:00:00
4  LDSMFG_163053  2025-01-25       READ              NaN  2025-01-25 10:00:00

In [3]:
wa['sent_at'] = pd.to_datetime(wa['sent_at'])
wa['read_at'] = pd.to_datetime(wa['read_at'])

In [4]:
wa_features = wa.groupby('lead_code').agg(
    wa_msgs_sent=('sent_at', 'count'),
    wa_msgs_read=('status', lambda x: (x == 'READ').sum()),
    wa_msgs_failed=('status', lambda x: (x == 'FAILED').sum()),
    wa_unique_responses=('response_message', 'nunique')
).reset_index()

wa_features.head()

,lead_code,wa_msgs_sent,wa_msgs_read,wa_msgs_failed,wa_unique_responses
0,LDSMFG_100000,3,2,1,0
1,LDSMFG_100002,3,0,0,0
2,LDSMFG_100003,2,0,0,0
3,LDSMFG_100004,3,2,0,0
4,LDSMFG_100005,3,2,1,0

In [5]:
bot = pd.read_csv("../data/teleco_call_back.csv")
bot.head()

       lead_code call_type disposition  duration  start_time transcript_json
0  LDSMFG_169928       BOT        BUSY        62  2025-01-03              {}
1  LDSMFG_118994       BOT   NO_ANSWER       153  2025-01-18              {}
2  LDSMFG_196829       BOT   NO_ANSWER       220  2025-01-12              {}
3  LDSMFG_138730       BOT   NO_ANSWER       196  2025-01-04              {}
4  LDSMFG_175894       BOT   NO_ANSWER       133  2025-01-10              {}

In [6]:
bot_features = bot.groupby('lead_code').agg(
    bot_calls=('start_time', 'count'),
    bot_answered=('disposition', lambda x: (x == 'ANSWERED').sum()),
    bot_avg_duration=('duration', 'mean')
).reset_index()

bot_features.head()

       lead_code  bot_calls  bot_answered  bot_avg_duration
0  LDSMFG_100000          2             0              14.5
1  LDSMFG_100002          2             0             214.0
2  LDSMFG_100003          1             1              51.0
3  LDSMFG_100004          3             2             114.0
4  LDSMFG_100005          1             0             252.0

In [7]:
human = pd.read_csv("../data/call_placed.csv")
human.head()

       lead_code call_type disposition  duration  start_time agent_id
0  LDSMFG_165406     HUMAN   NO_ANSWER       195  2025-01-11   AG_117
1  LDSMFG_193330     HUMAN   NO_ANSWER       208  2025-01-23   AG_146
2  LDSMFG_130724     HUMAN   NO_ANSWER       100  2025-01-29   AG_120
3  LDSMFG_138711     HUMAN        BUSY        89  2025-01-26   AG_101
4  LDSMFG_153922     HUMAN    ANSWERED       229  2025-01-15   AG_133

In [8]:
human_features = human.groupby('lead_code').agg(
    human_calls=('start_time', 'count'),
    human_answered=('disposition', lambda x: (x == 'ANSWERED').sum()),
    human_avg_duration=('duration', 'mean')
).reset_index()

human_features.head()

       lead_code  human_calls  human_answered  human_avg_duration
0  LDSMFG_100001            2               0               140.0
1  LDSMFG_100002            2               0                90.0
2  LDSMFG_100004            1               0                77.0
3  LDSMFG_100006            1               0               195.0
4  LDSMFG_100008            1               0               101.0

In [9]:
field = pd.read_csv("../data/mobile_app_data.csv")
field.head()

,lead_code,visit_date,latitude,longitude,result,remarks
0,LDSMFG_165067,2025-01-08,21.555155,77.611374,MET_CUSTOMER,Visited location
1,LDSMFG_179028,2025-01-23,19.801361,77.559830,SHIFTED,Visited location
2,LDSMFG_103580,2025-01-24,18.338005,77.592332,MET_CUSTOMER,Visited location
3,LDSMFG_114426,2025-01-07,21.868144,77.775007,DOOR_LOCKED,Visited location
4,LDSMFG_170042,2025-01-13,14.782281,77.530485,DOOR_LOCKED,Visited location

In [10]:
field_features = field.groupby('lead_code').agg(
    field_visits=('visit_date', 'count'),
    met_customer=('result', lambda x: (x == 'MET_CUSTOMER').sum()),
    door_locked=('result', lambda x: (x == 'DOOR_LOCKED').sum()),
    shifted=('result', lambda x: (x == 'SHIFTED').sum())
).reset_index()

field_features.head()

       lead_code  field_visits  met_customer  door_locked  shifted
0  LDSMFG_100009             1             0            0        1
1  LDSMFG_100011             1             0            0        1
2  LDSMFG_100012             1             1            0        0
3  LDSMFG_100014             2             0            0        2
4  LDSMFG_100015             1             0            0        1

In [11]:
sms = pd.read_csv("../data/AI_sms_callback.csv")
sms.head()

       lead_code     status
0  LDSMFG_110186  DELIVERED
1  LDSMFG_144016  DELIVERED
2  LDSMFG_105785  DELIVERED
3  LDSMFG_113650  DELIVERED
4  LDSMFG_121954  DELIVERED

In [12]:
sms_features = sms.groupby('lead_code').agg(
    sms_sent=('status', 'count'),
    sms_failed=('status', lambda x: (x != 'DELIVERED').sum())
).reset_index()

sms_features.head()

       lead_code  sms_sent  sms_failed
0  LDSMFG_100051         1           0
1  LDSMFG_100115         1           0
2  LDSMFG_100164         1           0
3  LDSMFG_100303         1           0
4  LDSMFG_100726         1           0

In [13]:
customer_360 = wa_features \
    .merge(bot_features, on='lead_code', how='outer') \
    .merge(human_features, on='lead_code', how='outer') \
    .merge(field_features, on='lead_code', how='outer') \
    .merge(sms_features, on='lead_code', how='outer')

customer_360.head()

,lead_code,wa_msgs_sent,wa_msgs_read,wa_msgs_failed,wa_unique_responses,bot_calls,bot_answered,bot_avg_duration,human_calls,human_answered,human_avg_duration,field_visits,met_customer,door_locked,shifted,sms_sent,sms_failed
0,LDSMFG_100000,3.0,2.0,1.0,0.0,2.0,0.0,14.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LDSMFG_100001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,140.0,NaN,NaN,NaN,NaN,NaN,NaN
2,LDSMFG_100002,3.0,0.0,0.0,0.0,2.0,0.0,214.0,2.0,0.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN
3,LDSMFG_100003,2.0,0.0,0.0,0.0,1.0,1.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LDSMFG_100004,3.0,2.0,0.0,0.0,3.0,2.0,114.0,1.0,0.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
customer_360 = customer_360.fillna(0)
customer_360.head()

,lead_code,wa_msgs_sent,wa_msgs_read,wa_msgs_failed,wa_unique_responses,bot_calls,bot_answered,bot_avg_duration,human_calls,human_answered,human_avg_duration,field_visits,met_customer,door_locked,shifted,sms_sent,sms_failed
0,LDSMFG_100000,3.0,2.0,1.0,0.0,2.0,0.0,14.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,LDSMFG_100001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,140.0,0.0,0.0,0.0,0.0,0.0,0.0
2,LDSMFG_100002,3.0,0.0,0.0,0.0,2.0,0.0,214.0,2.0,0.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0
3,LDSMFG_100003,2.0,0.0,0.0,0.0,1.0,1.0,51.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,LDSMFG_100004,3.0,2.0,0.0,0.0,3.0,2.0,114.0,1.0,0.0,77.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
customer_360.to_csv("../data/customer_360_features.csv", index=False)
customer_360 = customer_360.fillna(0)